### ISSUE TITLE
Link to existing PRONOM archive instead of xml export tool

### ISSUE THREAD

**Issue by ross-spencer** [timothyryanwalsh/addext#1]
Hi Tim,

Great work again. 

My archive of PRONOM files is here: https://github.com/exponential-decay/pronom-archive-and-skeleton-test-suite

Normally, it fairly accurately points to the latest release under releases but I see it says v91 instead of v92. I only have a rough idea why this is - it would take a bit of time for me to get my head around correcting it. v92 is there however, and I am working to make DOIs for each one I publish.  

The DOIs are in the README.md, so for v92, you'd go to: https://zenodo.org/record/1004423#.WgoFZ2GWa00

Under that set of files you'd point your users to: 

     pronom-export-{date}-sig-file-v{version no.}.zip

I understand for better provenance why the XML download would be desirable as well.

**Comment by tw4l** [comment]
Hi Ross,

Thanks for the encouragement! Change made :)

I imagine it will most likely be me updating `pronom.db` for new releases of the tool, but I've added this info into the README so that it should be apparent to anyone who wants to pick it up and we can spare the good folks at TNA all the unnecessary crawls.

Thanks!

**Comment by ross-spencer** [comment]
Aye! I do all my updates manually as well - including the-fr.org when i remember :\

But! @richardlehane shared this with me: https://github.com/richardlehane/builder

I don't know when I'll get the time to automate my downloads and subsequent generation of code/archives etc. But maybe it is something you can leverage for this? 

I don't know if you ever saw either, but back in the day we made the release notes a huge chunk of XML in their own right: https://www.nationalarchives.gov.uk/aboutapps/pronom/release-notes.xml 

I've been meaning to write a service to check daily for a new version and flag it for interested folks. Got half way in PHP before being distracted. Might be something to help with automation for both you and Richard. 

</infodump> ^_^;

**Comment by tw4l** [comment]
Oh hey, that's cool! And definitely potentially useful... it'll have to go onto the backburner to-do list for now as other projects are more pressing, but I do enjoy a tidy little project and will keep this in mind!

The service to flag for new versions sounds like a great idea too! Though I'm addicted enough to Twitter at this point that I usually catch the new releases within a few hours or so ;)

**Comment by ross-spencer** [comment]
I think Twitter is what stopped my progress with it somewhat too!! :D

**Comment by richardlehane** [comment]
there may be an opportunity for a shared infrastructure here... i.e. no need for us all to separately harvest PRONOM? 

Happy to add you both as committers to /builder (so anyone could trigger a new release) or assist in tailoring the .travis script for a shared repository?
